### ISSUE TITLE
Tilda is not properly expanded?

### ISSUE THREAD

**Issue by cultab** [pinpox/base16-universal-manager#33]
Using this in my config.yaml

```yaml
    vim:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default: ~/.config/nvim/colors
```
Causes base16 to create a file called '~' in it's config directory (~/.config/base16-universal-manager) and it doesn't actually write to the file it should. Using a path like "/home/username/.config/nvim/colors" works as expected. 

I spend too much time wondering why this didn't work so I'm tired and might have missed important information, please ask and I'll get it for you.
