### ISSUE TITLE
Support for multiple applications with the same template

### ISSUE THREAD

**Issue by jo1gi** [pinpox/base16-universal-manager#38]
I was wondering if it should be possible to add multiple applications per template since some applications use the same template (e.g. vim and neovim or anything that uses css). It could be done by adding a "template" option which would overwrite the normal template.

**Comment by pinpox** [comment]
What would be the benefit apart from having a shorter config?

**Comment by jo1gi** [comment]
Correct me if I am wrong, but I don't think it is possible to use the same template in multiple applications. There is for example a lot of applications that use the CSS template (https://github.com/samme/base16-styles). What I meant by adding a template option was something like this:
```yaml
applications:
  firefox:
    enabled: true
    template: css
    files:
      path: path/to/firefox/css

  discord:
    enabled: true
    template: css
    files:
      path: path/to/discord/css
```
