### ISSUE TITLE
Unmarshal Errors

### ISSUE THREAD

**Issue by c3lphie** [pinpox/base16-universal-manager#42]
When I run the software i keep getting unmarshall errors for my default config files

```
➜  ~ base16-universal-manager --scheme dracula
panic: yaml: unmarshal errors:
  line 68: cannot unmarshal !!str `~/.conf...` into main.FileConfig

goroutine 1 [running]:
main.check(...)
        /home/c3lphie/go/src/github.com/pinpox/base16-universal-manager/main.go:206
main.NewConfig(0xc00001a4c0, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/c3lphie/go/src/github.com/pinpox/base16-universal-manager/config.go:58 +0x55e
main.main()
        /home/c3lphie/go/src/github.com/pinpox/base16-universal-manager/main.go:39 +0x78
```
Here is a snippet of my config where the problem occures
```
    dunst:
        enabled: false 
        mode: rewrite
        hook: ""
        files:
          default: "~/.config/dunst/dunstrc"
```

I use arch btw ;)

I hope i can get some help with this :)

**Comment by c3lphie** [comment]
I fixed the issue myself by adding `path` to default

But maybe it should be made more clear in the readme

Solution:
```
    dunst:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: "~/.config/dunst/dunstrc"
```
